"use strict"; 

module.exports = { 
	INITIALIZE: "INITIALIZE",
	CREATE_AUTHOR: "CREATE_AUTHOR", 
	UPDATE_AUTHOR: "UPDATE_AUTHOR",
	UPDATE_NODES: "UPDATE_NODES",
	RESET_CHART: "RESET_CHART",
	SAVE_TEXT: "SAVE_TEXT"
};